language: java
sudo: true
jdk: oraclejdk11
dist: trusty
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)